// <auto-generated />
namespace stockManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DecimalPrecisionTo18ScaleAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecimalPrecisionTo18ScaleAll));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241831070_DecimalPrecisionTo18ScaleAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
